//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gerenciamento_mercadoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercadoria
    {
        public int MercadoriaId { get; set; }
        public string Nome { get; set; }
        public string NumeroRegistro { get; set; }
        public string Fabricante { get; set; }
        public int Tipo { get; set; }
        public string Descricao { get; set; }
    
        public virtual Tipo Tipos { get; set; }
    }
}
