//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gerenciamento_mercadoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Mercadorias = new HashSet<Mercadoria>();
        }
    
        public int TipoId { get; set; }
        public string TipoNome { get; set; }
    
        public virtual ICollection<Mercadoria> Mercadorias { get; set; }
    }
}
